/*
 * SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * Vendor quirks for the OTG controller of the STM32MP1 series. The controller
 * uses port 1 of the USBPHYC USB HS PHY, initialized before the controller by
 * its own driver, and the 48 MHz clock generated by the PHY as kernel clock.
 */

#ifndef ZEPHYR_DRIVERS_USB_UDC_DWC2_STM32MP1_HSOTG_H
#define ZEPHYR_DRIVERS_USB_UDC_DWC2_STM32MP1_HSOTG_H

#include <soc.h>
#include <stm32_ll_rcc.h>

#include <zephyr/device.h>
#include <zephyr/drivers/clock_control.h>
#include <zephyr/drivers/clock_control/stm32_clock_control.h>
#include <zephyr/drivers/reset.h>
#include <zephyr/sys/sys_io.h>
#include <usb_dwc2_hw.h>

/* GOTGCTL B-session valid override, 5.3.1 of the DWC2 databook */
#define DWC2_STM32MP1_GOTGCTL_BVALOEN	BIT(6)
#define DWC2_STM32MP1_GOTGCTL_BVALOVAL	BIT(7)

struct dwc2_stm32mp1_config {
	struct stm32_pclken pclken;
	struct reset_dt_spec reset;
};

static inline int stm32mp1_hsotg_init(const struct dwc2_stm32mp1_config *const cfg)
{
	const struct device *rcc = DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE);
	int ret;

	if (!device_is_ready(rcc)) {
		return -ENODEV;
	}

	/* The kernel clock of the controller is the 48 MHz clock of the PHY */
	LL_RCC_SetUSBOClockSource(LL_RCC_USBO_CLKSOURCE_PHY);

	ret = clock_control_on(rcc, (clock_control_subsys_t)&cfg->pclken);
	if (ret != 0) {
		return ret;
	}

	return reset_line_toggle_dt(&cfg->reset);
}

/*
 * There is no VBUS or ID detection, the role is handled by the Type-C
 * controller of the board. Override the B-session valid signal so the
 * controller connects as soon as the pull-up is enabled.
 */
static inline int stm32mp1_hsotg_post_enable(const struct device *dev)
{
	struct usb_dwc2_reg *const base = dwc2_get_base(dev);

	sys_set_bits((mem_addr_t)&base->gotgctl,
		     DWC2_STM32MP1_GOTGCTL_BVALOEN | DWC2_STM32MP1_GOTGCTL_BVALOVAL);

	return 0;
}

static inline int stm32mp1_hsotg_disable(const struct device *dev)
{
	struct usb_dwc2_reg *const base = dwc2_get_base(dev);

	sys_clear_bits((mem_addr_t)&base->gotgctl,
		       DWC2_STM32MP1_GOTGCTL_BVALOEN | DWC2_STM32MP1_GOTGCTL_BVALOVAL);

	return 0;
}

#define QUIRK_STM32MP1_HSOTG_DEFINE(n)							\
	static const struct dwc2_stm32mp1_config dwc2_stm32mp1_config_##n = {		\
		.pclken = STM32_CLOCK_INFO(0, DT_DRV_INST(n)),				\
		.reset = RESET_DT_SPEC_INST_GET(n),					\
	};										\
											\
	static int stm32mp1_hsotg_init_##n(const struct device *dev)			\
	{										\
		ARG_UNUSED(dev);							\
		return stm32mp1_hsotg_init(&dwc2_stm32mp1_config_##n);			\
	}										\
											\
	const struct dwc2_vendor_quirks dwc2_vendor_quirks_##n = {			\
		.init = stm32mp1_hsotg_init_##n,					\
		.post_enable = stm32mp1_hsotg_post_enable,				\
		.disable = stm32mp1_hsotg_disable,					\
	};

DT_INST_FOREACH_STATUS_OKAY(QUIRK_STM32MP1_HSOTG_DEFINE)

#endif /* ZEPHYR_DRIVERS_USB_UDC_DWC2_STM32MP1_HSOTG_H */
